#!/bin/bash

binDir=`dirname "$0"`

cd $binDir

export HADOOP_CLASSPATH=$binDir/JRecordV2.jar


/usr/bin/hadoop jar $binDir/copybook2tsv.jar org.apache.hadoop.copybook2tsv.mapred.CopybookDriver -Dmapred.job.queue.name=ingest "$@"